module.exports = [
  {
    ingredients_id: 5165,
    name: 'turkey',
    costValue: 950.21,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-raw-whole.jpg',
    aisle: 'Meat',
    percentageProtein: 63.04,
    percentageFat: 36.96,
    percentageCarbs: 0
  },
  {
    ingredients_id: 98961,
    name: 'summer savory',
    costValue: 6.04,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/summer-savory.jpg',
    aisle: 'Produce',
    percentageProtein: 7.56,
    percentageFat: 14.97,
    percentageCarbs: 77.47
  },
  {
    ingredients_id: 5696,
    name: 'boneless turkey breasts',
    costValue: 379.6,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-breast.jpg',
    aisle: 'Meat',
    percentageProtein: 85.22,
    percentageFat: 14.78,
    percentageCarbs: 0
  },
  {
    ingredients_id: 1002028,
    name: 'hungarian paprika',
    costValue: 2.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/paprika.jpg',
    aisle: 'Spices and Seasonings',
    percentageProtein: 14.56,
    percentageFat: 29.86,
    percentageCarbs: 55.58
  },
  {
    ingredients_id: 43155,
    name: 'sparkling wine',
    costValue: 1.47,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/champagne.png',
    aisle: 'Alcoholic Beverages',
    percentageProtein: 0.28,
    percentageFat: 0,
    percentageCarbs: 99.72
  },
  {
    ingredients_id: 93695,
    name: 'steel oats',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/steel-cut-oats.png',
    aisle: 'Cereal',
    percentageProtein: 16.37,
    percentageFat: 16.11,
    percentageCarbs: 67.52
  },
  {
    ingredients_id: 10011485,
    name: 'squash',
    costValue: 165,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/butternut-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.74,
    percentageFat: 1.74,
    percentageCarbs: 90.52
  },
  {
    ingredients_id: 10023618,
    name: 'beef cubes',
    costValue: 0.78,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/beef-cubes-raw.png',
    aisle: 'Meat',
    percentageProtein: 66.57,
    percentageFat: 33.43,
    percentageCarbs: 0
  },
  {
    ingredients_id: 10011457,
    name: 'spinach leaves',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spinach.jpg',
    aisle: 'Produce',
    percentageProtein: 38.82,
    percentageFat: 11.91,
    percentageCarbs: 49.27
  },
  {
    ingredients_id: 11492,
    name: 'spaghetti squashes',
    costValue: 319.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spaghetti-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.25,
    percentageFat: 14.52,
    percentageCarbs: 78.23
  },
  {
    ingredients_id: 11641,
    name: 'summer squash',
    costValue: 86.68,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/yellow-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 24.37,
    percentageFat: 8.16,
    percentageCarbs: 67.47
  },
  {
    ingredients_id: 12036,
    name: 'sunflower seed',
    costValue: 0.75,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sunflower-seeds.jpg',
    aisle: 'Savory Snacks',
    percentageProtein: 13.27,
    percentageFat: 73.95,
    percentageCarbs: 12.78
  },
  {
    ingredients_id: 11001,
    name: 'microgreens',
    costValue: 0.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/alfalfa-sprouts.png',
    aisle: 'Produce',
    percentageProtein: 52.21,
    percentageFat: 20.31,
    percentageCarbs: 27.48
  },
  {
    ingredients_id: 4584,
    name: 'sunflower oil',
    costValue: 1.36,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/vegetable-oil.jpg',
    aisle: 'Oil, Vinegar, Salad Dressing',
    percentageProtein: 0,
    percentageFat: 100,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11583,
    name: 'vegetable mix',
    costValue: 0.39,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/mixed-vegetables.png',
    aisle: 'Frozen',
    percentageProtein: 18.54,
    percentageFat: 6.51,
    percentageCarbs: 74.95
  },
  {
    ingredients_id: 23584,
    name: 'beef top sirloin steak',
    costValue: 351.05,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/top-sirloin-steak.jpg',
    aisle: 'Meat',
    percentageProtein: 73.66,
    percentageFat: 26.34,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11294,
    name: 'sweet yellow onion',
    costValue: 94.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sweet-onion.png',
    aisle: 'Produce',
    percentageProtein: 9.38,
    percentageFat: 2.11,
    percentageCarbs: 88.51
  },
  {
    ingredients_id: 10819297,
    name: 'strawberry fruit spread',
    costValue: 1.25,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/strawberry-jam.png',
    aisle: 'Nut butters, Jams, and Honey',
    percentageProtein: 0.53,
    percentageFat: 0.23,
    percentageCarbs: 99.24
  },
  {
    ingredients_id: 5165,
    name: 'turkey',
    costValue: 950.21,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-raw-whole.jpg',
    aisle: 'Meat',
    percentageProtein: 63.04,
    percentageFat: 36.96,
    percentageCarbs: 0
  },
  {
    ingredients_id: 98961,
    name: 'summer savory',
    costValue: 6.04,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/summer-savory.jpg',
    aisle: 'Produce',
    percentageProtein: 7.56,
    percentageFat: 14.97,
    percentageCarbs: 77.47
  },
  {
    ingredients_id: 93640,
    name: 'sweet pickle juice',
    costValue: 0.82,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/pickle-juice.jpg',
    aisle: 'Canned and Jarred',
    percentageProtein: 0,
    percentageFat: 0,
    percentageCarbs: 100
  },
  {
    ingredients_id: 5696,
    name: 'boneless turkey breasts',
    costValue: 379.6,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-breast.jpg',
    aisle: 'Meat',
    percentageProtein: 85.22,
    percentageFat: 14.78,
    percentageCarbs: 0
  },
  {
    ingredients_id: 1002028,
    name: 'hungarian paprika',
    costValue: 2.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/paprika.jpg',
    aisle: 'Spices and Seasonings',
    percentageProtein: 14.56,
    percentageFat: 29.86,
    percentageCarbs: 55.58
  },
  {
    ingredients_id: 43155,
    name: 'sparkling wine',
    costValue: 1.47,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/champagne.png',
    aisle: 'Alcoholic Beverages',
    percentageProtein: 0.28,
    percentageFat: 0,
    percentageCarbs: 99.72
  },
  {
    ingredients_id: 93695,
    name: 'steel oats',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/steel-cut-oats.png',
    aisle: 'Cereal',
    percentageProtein: 16.37,
    percentageFat: 16.11,
    percentageCarbs: 67.52
  },
  {
    ingredients_id: 10011485,
    name: 'squash',
    costValue: 165,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/butternut-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.74,
    percentageFat: 1.74,
    percentageCarbs: 90.52
  },
  {
    ingredients_id: 10023618,
    name: 'beef cubes',
    costValue: 0.78,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/beef-cubes-raw.png',
    aisle: 'Meat',
    percentageProtein: 66.57,
    percentageFat: 33.43,
    percentageCarbs: 0
  },
  {
    ingredients_id: 10011457,
    name: 'spinach leaves',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spinach.jpg',
    aisle: 'Produce',
    percentageProtein: 38.82,
    percentageFat: 11.91,
    percentageCarbs: 49.27
  },
  {
    ingredients_id: 11492,
    name: 'spaghetti squashes',
    costValue: 319.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spaghetti-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.25,
    percentageFat: 14.52,
    percentageCarbs: 78.23
  },
  {
    ingredients_id: 11641,
    name: 'summer squash',
    costValue: 86.68,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/yellow-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 24.37,
    percentageFat: 8.16,
    percentageCarbs: 67.47
  },
  {
    ingredients_id: 12036,
    name: 'sunflower seed',
    costValue: 0.75,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sunflower-seeds.jpg',
    aisle: 'Savory Snacks',
    percentageProtein: 13.27,
    percentageFat: 73.95,
    percentageCarbs: 12.78
  },
  {
    ingredients_id: 11001,
    name: 'microgreens',
    costValue: 0.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/alfalfa-sprouts.png',
    aisle: 'Produce',
    percentageProtein: 52.21,
    percentageFat: 20.31,
    percentageCarbs: 27.48
  },
  {
    ingredients_id: 4584,
    name: 'sunflower oil',
    costValue: 1.36,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/vegetable-oil.jpg',
    aisle: 'Oil, Vinegar, Salad Dressing',
    percentageProtein: 0,
    percentageFat: 100,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11583,
    name: 'vegetable mix',
    costValue: 0.39,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/mixed-vegetables.png',
    aisle: 'Frozen',
    percentageProtein: 18.54,
    percentageFat: 6.51,
    percentageCarbs: 74.95
  },
  {
    ingredients_id: 23584,
    name: 'beef top sirloin steak',
    costValue: 351.05,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/top-sirloin-steak.jpg',
    aisle: 'Meat',
    percentageProtein: 73.66,
    percentageFat: 26.34,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11294,
    name: 'sweet yellow onion',
    costValue: 94.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sweet-onion.png',
    aisle: 'Produce',
    percentageProtein: 9.38,
    percentageFat: 2.11,
    percentageCarbs: 88.51
  },
  {
    ingredients_id: 10819297,
    name: 'strawberry fruit spread',
    costValue: 1.25,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/strawberry-jam.png',
    aisle: 'Nut butters, Jams, and Honey',
    percentageProtein: 0.53,
    percentageFat: 0.23,
    percentageCarbs: 99.24
  },
  {
    ingredients_id: 5165,
    name: 'turkey',
    costValue: 950.21,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-raw-whole.jpg',
    aisle: 'Meat',
    percentageProtein: 63.04,
    percentageFat: 36.96,
    percentageCarbs: 0
  },
  {
    ingredients_id: 98961,
    name: 'summer savory',
    costValue: 6.04,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/summer-savory.jpg',
    aisle: 'Produce',
    percentageProtein: 7.56,
    percentageFat: 14.97,
    percentageCarbs: 77.47
  },
  {
    ingredients_id: 93640,
    name: 'sweet pickle juice',
    costValue: 0.82,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/pickle-juice.jpg',
    aisle: 'Canned and Jarred',
    percentageProtein: 0,
    percentageFat: 0,
    percentageCarbs: 100
  },
  {
    ingredients_id: 23232,
    name: 'steaks',
    costValue: 501.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/ribeye-raw.jpg',
    aisle: 'Meat',
    percentageProtein: 38.74,
    percentageFat: 61.26,
    percentageCarbs: 0
  },
  {
    ingredients_id: 5696,
    name: 'boneless turkey breasts',
    costValue: 379.6,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-breast.jpg',
    aisle: 'Meat',
    percentageProtein: 85.22,
    percentageFat: 14.78,
    percentageCarbs: 0
  },
  {
    ingredients_id: 1002028,
    name: 'hungarian paprika',
    costValue: 2.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/paprika.jpg',
    aisle: 'Spices and Seasonings',
    percentageProtein: 14.56,
    percentageFat: 29.86,
    percentageCarbs: 55.58
  },
  {
    ingredients_id: 43155,
    name: 'sparkling wine',
    costValue: 1.47,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/champagne.png',
    aisle: 'Alcoholic Beverages',
    percentageProtein: 0.28,
    percentageFat: 0,
    percentageCarbs: 99.72
  },
  {
    ingredients_id: 93695,
    name: 'steel oats',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/steel-cut-oats.png',
    aisle: 'Cereal',
    percentageProtein: 16.37,
    percentageFat: 16.11,
    percentageCarbs: 67.52
  },
  {
    ingredients_id: 10011485,
    name: 'squash',
    costValue: 165,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/butternut-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.74,
    percentageFat: 1.74,
    percentageCarbs: 90.52
  },
  {
    ingredients_id: 10023618,
    name: 'beef cubes',
    costValue: 0.78,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/beef-cubes-raw.png',
    aisle: 'Meat',
    percentageProtein: 66.57,
    percentageFat: 33.43,
    percentageCarbs: 0
  },
  {
    ingredients_id: 10011457,
    name: 'spinach leaves',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spinach.jpg',
    aisle: 'Produce',
    percentageProtein: 38.82,
    percentageFat: 11.91,
    percentageCarbs: 49.27
  },
  {
    ingredients_id: 11492,
    name: 'spaghetti squashes',
    costValue: 319.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spaghetti-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.25,
    percentageFat: 14.52,
    percentageCarbs: 78.23
  },
  {
    ingredients_id: 11641,
    name: 'summer squash',
    costValue: 86.68,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/yellow-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 24.37,
    percentageFat: 8.16,
    percentageCarbs: 67.47
  },
  {
    ingredients_id: 12036,
    name: 'sunflower seed',
    costValue: 0.75,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sunflower-seeds.jpg',
    aisle: 'Savory Snacks',
    percentageProtein: 13.27,
    percentageFat: 73.95,
    percentageCarbs: 12.78
  },
  {
    ingredients_id: 11001,
    name: 'microgreens',
    costValue: 0.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/alfalfa-sprouts.png',
    aisle: 'Produce',
    percentageProtein: 52.21,
    percentageFat: 20.31,
    percentageCarbs: 27.48
  },
  {
    ingredients_id: 4584,
    name: 'sunflower oil',
    costValue: 1.36,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/vegetable-oil.jpg',
    aisle: 'Oil, Vinegar, Salad Dressing',
    percentageProtein: 0,
    percentageFat: 100,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11583,
    name: 'vegetable mix',
    costValue: 0.39,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/mixed-vegetables.png',
    aisle: 'Frozen',
    percentageProtein: 18.54,
    percentageFat: 6.51,
    percentageCarbs: 74.95
  },
  {
    ingredients_id: 23584,
    name: 'beef top sirloin steak',
    costValue: 351.05,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/top-sirloin-steak.jpg',
    aisle: 'Meat',
    percentageProtein: 73.66,
    percentageFat: 26.34,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11294,
    name: 'sweet yellow onion',
    costValue: 94.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sweet-onion.png',
    aisle: 'Produce',
    percentageProtein: 9.38,
    percentageFat: 2.11,
    percentageCarbs: 88.51
  },
  {
    ingredients_id: 10819297,
    name: 'strawberry fruit spread',
    costValue: 1.25,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/strawberry-jam.png',
    aisle: 'Nut butters, Jams, and Honey',
    percentageProtein: 0.53,
    percentageFat: 0.23,
    percentageCarbs: 99.24
  },
  {
    ingredients_id: 5165,
    name: 'turkey',
    costValue: 950.21,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-raw-whole.jpg',
    aisle: 'Meat',
    percentageProtein: 63.04,
    percentageFat: 36.96,
    percentageCarbs: 0
  },
  {
    ingredients_id: 98961,
    name: 'summer savory',
    costValue: 6.04,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/summer-savory.jpg',
    aisle: 'Produce',
    percentageProtein: 7.56,
    percentageFat: 14.97,
    percentageCarbs: 77.47
  },
  {
    ingredients_id: 93640,
    name: 'sweet pickle juice',
    costValue: 0.82,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/pickle-juice.jpg',
    aisle: 'Canned and Jarred',
    percentageProtein: 0,
    percentageFat: 0,
    percentageCarbs: 100
  },
  {
    ingredients_id: 23232,
    name: 'steaks',
    costValue: 501.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/ribeye-raw.jpg',
    aisle: 'Meat',
    percentageProtein: 38.74,
    percentageFat: 61.26,
    percentageCarbs: 0
  },
  {
    ingredients_id: 9316,
    name: 'strawberry',
    costValue: 10.71,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/strawberries.png',
    aisle: 'Produce',
    percentageProtein: 7.42,
    percentageFat: 7.48,
    percentageCarbs: 85.1
  },
  {
    ingredients_id: 5696,
    name: 'boneless turkey breasts',
    costValue: 379.6,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-breast.jpg',
    aisle: 'Meat',
    percentageProtein: 85.22,
    percentageFat: 14.78,
    percentageCarbs: 0
  },
  {
    ingredients_id: 1002028,
    name: 'hungarian paprika',
    costValue: 2.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/paprika.jpg',
    aisle: 'Spices and Seasonings',
    percentageProtein: 14.56,
    percentageFat: 29.86,
    percentageCarbs: 55.58
  },
  {
    ingredients_id: 43155,
    name: 'sparkling wine',
    costValue: 1.47,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/champagne.png',
    aisle: 'Alcoholic Beverages',
    percentageProtein: 0.28,
    percentageFat: 0,
    percentageCarbs: 99.72
  },
  {
    ingredients_id: 93695,
    name: 'steel oats',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/steel-cut-oats.png',
    aisle: 'Cereal',
    percentageProtein: 16.37,
    percentageFat: 16.11,
    percentageCarbs: 67.52
  },
  {
    ingredients_id: 10011485,
    name: 'squash',
    costValue: 165,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/butternut-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.74,
    percentageFat: 1.74,
    percentageCarbs: 90.52
  },
  {
    ingredients_id: 10023618,
    name: 'beef cubes',
    costValue: 0.78,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/beef-cubes-raw.png',
    aisle: 'Meat',
    percentageProtein: 66.57,
    percentageFat: 33.43,
    percentageCarbs: 0
  },
  {
    ingredients_id: 10011457,
    name: 'spinach leaves',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spinach.jpg',
    aisle: 'Produce',
    percentageProtein: 38.82,
    percentageFat: 11.91,
    percentageCarbs: 49.27
  },
  {
    ingredients_id: 11492,
    name: 'spaghetti squashes',
    costValue: 319.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/spaghetti-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 7.25,
    percentageFat: 14.52,
    percentageCarbs: 78.23
  },
  {
    ingredients_id: 11641,
    name: 'summer squash',
    costValue: 86.68,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/yellow-squash.jpg',
    aisle: 'Produce',
    percentageProtein: 24.37,
    percentageFat: 8.16,
    percentageCarbs: 67.47
  },
  {
    ingredients_id: 12036,
    name: 'sunflower seed',
    costValue: 0.75,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sunflower-seeds.jpg',
    aisle: 'Savory Snacks',
    percentageProtein: 13.27,
    percentageFat: 73.95,
    percentageCarbs: 12.78
  },
  {
    ingredients_id: 11001,
    name: 'microgreens',
    costValue: 0.93,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/alfalfa-sprouts.png',
    aisle: 'Produce',
    percentageProtein: 52.21,
    percentageFat: 20.31,
    percentageCarbs: 27.48
  },
  {
    ingredients_id: 4584,
    name: 'sunflower oil',
    costValue: 1.36,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/vegetable-oil.jpg',
    aisle: 'Oil, Vinegar, Salad Dressing',
    percentageProtein: 0,
    percentageFat: 100,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11583,
    name: 'vegetable mix',
    costValue: 0.39,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/mixed-vegetables.png',
    aisle: 'Frozen',
    percentageProtein: 18.54,
    percentageFat: 6.51,
    percentageCarbs: 74.95
  },
  {
    ingredients_id: 23584,
    name: 'beef top sirloin steak',
    costValue: 351.05,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/top-sirloin-steak.jpg',
    aisle: 'Meat',
    percentageProtein: 73.66,
    percentageFat: 26.34,
    percentageCarbs: 0
  },
  {
    ingredients_id: 11294,
    name: 'sweet yellow onion',
    costValue: 94.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sweet-onion.png',
    aisle: 'Produce',
    percentageProtein: 9.38,
    percentageFat: 2.11,
    percentageCarbs: 88.51
  },
  {
    ingredients_id: 10819297,
    name: 'strawberry fruit spread',
    costValue: 1.25,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/strawberry-jam.png',
    aisle: 'Nut butters, Jams, and Honey',
    percentageProtein: 0.53,
    percentageFat: 0.23,
    percentageCarbs: 99.24
  },
  {
    ingredients_id: 5165,
    name: 'turkey',
    costValue: 950.21,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/turkey-raw-whole.jpg',
    aisle: 'Meat',
    percentageProtein: 63.04,
    percentageFat: 36.96,
    percentageCarbs: 0
  },
  {
    ingredients_id: 98961,
    name: 'summer savory',
    costValue: 6.04,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/summer-savory.jpg',
    aisle: 'Produce',
    percentageProtein: 7.56,
    percentageFat: 14.97,
    percentageCarbs: 77.47
  },
  {
    ingredients_id: 93640,
    name: 'sweet pickle juice',
    costValue: 0.82,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/pickle-juice.jpg',
    aisle: 'Canned and Jarred',
    percentageProtein: 0,
    percentageFat: 0,
    percentageCarbs: 100
  },
  {
    ingredients_id: 23232,
    name: 'steaks',
    costValue: 501.72,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/ribeye-raw.jpg',
    aisle: 'Meat',
    percentageProtein: 38.74,
    percentageFat: 61.26,
    percentageCarbs: 0
  },
  {
    ingredients_id: 9316,
    name: 'strawberry',
    costValue: 10.71,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/strawberries.png',
    aisle: 'Produce',
    percentageProtein: 7.42,
    percentageFat: 7.48,
    percentageCarbs: 85.1
  },
  {
    ingredients_id: 10011300,
    name: 'snap peas',
    costValue: 0.89,
    costUnit: 'US Cents',
    image: 'https://spoonacular.com/cdn/ingredients_250x250/sugar-snap-peas.jpg',
    aisle: 'Produce',
    percentageProtein: 25.93,
    percentageFat: 4.17,
    percentageCarbs: 69.9
  }
]